Just use git blame output

diff --git a/git-timemachine b/git-timemachine
--- a/git-timemachine
+++ b/git-timemachine
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash 
 # Prints the content of a given file, or specific lines of that file, for each revision.
 # Based on http://stackoverflow.com/questions/17785265/list-all-the-versions-of-a-given-line-number-in-the-git-history
 # Place this somewhere in your path and you can invoke it with `git timemachine ...` (see full usage below)
@@ -50,20 +50,36 @@ if [ $# -eq 3 ]; then
 fi
 
 function clean() {
-    echo "$1" | sed 's/^.*[0-9])  //'
+    echo "$@" | sed 's/^.*[0-9])  //'
 }
 
 function show() {
-    echo "$1" | sed 's/^\(.*[0-9])\)  \(.*\)$/== As of commit \1 ==\n\2\n/'
+    echo "$@" 
+    echo "----"
 }
 
-OLD="" 
+if [ ! -e "$FILE" ]; then
+    echo "ERROR: file does not exist - '$FILE'" >&2
+    exit 3
+fi
+
+
+OLD="==first entry==" 
 for REV in $(git log --format=format:%H $FILE)
 do
-    NEW=$(git blame $FILE $LINES $REV 2>/dev/null || echo "No match")
-    if [ "$(clean $OLD)" != "$(clean $NEW)" ]
-    then 
-        show $NEW
+    if [ "$OLD" = "==first entry==" ]; then
+        OLD=$NEW
+        continue
+    fi
+    NEW=$(git blame $FILE $LINES $REV 2>/dev/null)
+    GIT_RETURN=$?
+    if [ "$(clean "$OLD")" != "$(clean "$NEW")" ]; then 
+        if [ $GIT_RETURN -eq 0 ]; then 
+            show "$NEW"
+        else
+            echo "== As of commit ${REV:0:8} =="
+            echo "NO MATCH"
+        fi
         OLD=$NEW
     fi
 done
